### ISSUE TITLE
Can not send report to qase with qase-robotframework

### ISSUE THREAD

**Issue by JungPham** [qase-tms/qase-python#247] opened 2024-08-22 17:36 UTC
Hi team,

I ran with `qase-robotframework==3.0.0`, `robotframework==7.0` and can not complete run on QASE.
Command:
```
 robot --listener qase.robotframework.Listener -d Report -v headless:True -v env:dev -v browser:chrome TestSuites/Chat_Flow.robot
```

Error:
```
[Qase][23:56:59][error] Error at sending results for run 229: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 22 Aug 2024 16:56:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, private', 'X-RateLimit-Limit': '1500', 'X-RateLimit-Remaining': '1496', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: {"status":false,"errorMessage":"Data is invalid.","errorFields":[{"field":"results.0.steps.0.steps.1.action","error":"The action must be a string."},{"field":"results.0.steps.0.steps.1","error":"Invalid step result definition."},{"field":"results.0.steps.0","error":"Invalid step result definition."},{"field":"results.0.steps.3.steps.11.steps.1.action","error":"The action must be a string."},{"field":"results.0.steps.3.steps.11.steps.1","error":"Invalid step result definition."},{"field":"results.0.steps.3.steps.11","error":"Invalid step result definition."},{"field":"results.0.steps.3","error":"Invalid step result definition."},{"field":"results.0.steps.9.steps.3.steps.3.action","error":"The action must be a string."},{"field":"results.0.steps.9.steps.3.steps.3","error":"Invalid step result definition."},{"field":"results.0.steps.9.steps.3","error":"Invalid step result definition."},{"field":"results.0.steps.9","error":"Invalid step result definition."},{"field":"results.0","error":"Invalid step result definition."}]}


Exception in thread Thread-3 (_send_results_threaded):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run    
    self._target(*self._args, **self._kwargs)
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\reporters\testops.py", line 76, in _send_results_threaded 
    self.client.send_results(self.project_code, self.run_id, results)
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\client\api_v1_client.py", line 127, in send_results       
    api_results.create_result_bulk(
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\pydantic\validate_call_decorator.py", line 60, in wrapper_function     
    return validate_call_wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\pydantic\_internal\_validate_call.py", line 96, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\api_client_v1\api\results_api.py", line 445, in create_result_bulk    return self.api_client.response_deserialize(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\api_client_v1\api_client.py", line 321, in response_deserialize   
    raise ApiException.from_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\api_client_v1\exceptions.py", line 143, in from_response
    raise BadRequestException(http_resp=http_resp, body=body, data=data)
qase.api_client_v1.exceptions.BadRequestException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 22 Aug 2024 16:56:59 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, private', 'X-RateLimit-Limit': '1500', 'X-RateLimit-Remaining': '1496', 'Strict-Transport-Security': 'max-age=31536000; insport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: {"status":false,"errorMessage":"Data is invalid.","errorFields":[{"field":"results.0.steps.0.steps.1.action","error":"The action must be a string."},{"field":"restion must be a string."},{"field":"results.0.steps.0.steps.1","error":"Invalid step result definition."},{"field":"results.0.steps.0","error":"Ild":"results.0.steps.3.steps.11.steps.nvalid step result definition."},{"field":"results.0.steps.3.steps.11.steps.1.action","error":"The action must be a string."},{"field":"results.ld":"results.0.steps.3.steps.11","erro0.steps.3.steps.11.steps.1","error":"Invalid step result definition."},{"field":"results.0.steps.3.steps.11","error":"Invalid step result defini3.steps.3.action","error":"The action tion."},{"field":"results.0.steps.3","error":"Invalid step result definition."},{"field":"results.0.steps.9.steps.3.steps.3.action","error":"The,"error":"Invalid step result definiti action must be a string."},{"field":"results.0.steps.9.steps.3.steps.3","error":"Invalid step result definition."},{"field":"results.0.steps.9.steps.3","error":"Invalid step result definition."},{"field":"results.0.steps.9","error":"Invalid step result definition."},{"field":"results.0","error":"Invalid step result definition."}]}
```

I try to config debug: true in `qase.config.json` and rerun again, debug log:
```
[Qase][00:31:04][debug] Prepared result: {'status': 'passed', 'stacktrace': '', 'time_ms': 6923, 'comment': None, 'attachments': [], 'steps': [{'time': 1473, 'status': 'passed', 'action': 'Click On Team Members Menu', 'steps': [{'time': 1468, 'status': 'passed', 'action': '"${team_name}" == "担当者なし"', 'steps': [{'time': 1466, 'status': 'passed', 'action': 'Common Click Element', 'steps': [{'time': 1248, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 25, 'status': 'passed', 'action': '${scroll}', 'steps': [{'time': 24, 'status': 'passed', 'action': 'Scroll To Element', 'steps': [{'time': 12, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 11, 'status': 'passed', 'action': 
'Execute Javascript'}]}]}, {'time': 187, 'status': 'passed', 'action': 'Click Element'}]}]}, {'time': 3, 'status': 'blocked', 'action': '', 'steps': [{'time': 0, 'status': 'blocked', 'action': 'Common Click Element'}, {'time': 0, 'status': 'blocked', 'action': 'Run Keyword And Return Status'}, {'time': 1, 'status': 'blocked', 'action': '"${status}"=="${False}"', 'steps': [{'time': 0, 'status': 'blocked', 'action': 'Common Click 
Element'}, {'time': 0, 'status': 'blocked', 'action': 'Common Click Element'}]}]}]}, {'time': 1424, 'status': 'passed', 'action': 'Get Conversation Id', 'steps': [{'time': 423, 'status': 'passed', 'action': 'Common Click Element', 'steps': [{'time': 286, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 27, 'status': 'passed', 'action': '${scroll}', 'steps': [{'time': 26, 'status': 'passed', 'action': 'Scroll To Element', 'steps': [{'time': 11, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 14, 'status': 'passed', 'action': 'Execute Javascript'}]}]}, {'time': 101, 'status': 'passed', 'action': 'Click Element'}]}, {'time': 921, 'status': 'passed', 'action': 'Get Location'}, {'time': 2, 'status': 'passed', 'action': 'Split String'}, {'time': 10, 'status': 'passed', 'action': 'Set Variable'}, {'time': 35, 'status': 'passed', 'action': '${i}    IN    @{location}', 'steps': [{'time': 1, 'status': 'passed', 'action': '${i} = https://resola.deca-dev.com/livechat/?status=new', 'steps': [{'time': 1, 'status': 'blocked', 'action': '"cId=" in "${i}"', 'steps': [{'time': 0, 'status': 'blocked', 'action': 'Split String'}, {'time': 0, 'status': 'blocked', 'action': 'Set Variable'}]}]}, {'time': 1, 'status': 'passed', 'action': '${i} = assigned=false', 'steps': [{'time': 0, 'status': 'blocked', 'action': '"cId=" in "${i}"', 'steps': [{'time': 0, 'status': 'blocked', 'action': 'Split String'}, {'time': 0, 'status': 'blocked', 'action': 'Set Variable'}]}]}, {'time': 2, 'status': 'passed', 'action': '${i} = per_page=20', 'steps': [{'time': 0, 'status': 'blocked', 'action': '"cId=" in "${i}"', 'steps': [{'time': 0, 'status': 'blocked', 'action': 'Split String'}, {'time': 0, 'status': 
'blocked', 'action': 'Set Variable'}]}]}, {'time': 25, 'status': 'passed', 'action': '${i} = cId=01j5xj7z89vpm88akcctp8zqjf', 'steps': [{'time': 24, 'status': 'passed', 'action': '"cId=" in "${i}"', 'steps': [{'time': 14, 'status': 'passed', 'action': 'Split String'}, {'time': 5, 'status': 'passed', 'action': 'Set Variable'}]}]}]}, {'time': 12, 'status': 'passed', 'action': 'Set Suite Variable'}, {'time': 3, 'status': 'passed', 
'action': 'Log'}]}, {'time': 283, 'status': 'passed', 'action': 'Verify New Conversation Should Appear On No Assignee List', 'steps': [{'time': 
139, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 17, 'status': 'passed', 'action': 'Page Should Contain Element'}, 
{'time': 19, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 23, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 30, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 28, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 18, 'status': 'passed', 'action': 'Page Should Contain Element'}]}, {'time': 334, 'status': 'passed', 'action': 'Verify Conversation Infomation On Inbox', 'steps': [{'time': 51, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 16, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 26, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 0, 'status': 'passed', 'action': 'Split String'}, {'time': 3, 'status': 'passed', 'action': 'Set Variable'}, {'time': 32, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 0, 'status': 'passed', 'action': 'Remove String'}, {'time': 71, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 14, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 50, 'status': 'passed', 'action': 'Run Keyword If', 'steps': [{'time': 49, 'status': 'passed', 'action': 'Page Should Contain Element'}]}, {'time': 25, 'status': 'passed', 'action': 'Page Should Contain Element'}, {'time': 21, 'status': 'passed', 'action': 'JS Get Sender Name Align On Inbox', 'steps': [{'time': 19, 'status': 'passed', 'action': 'Execute Javascript'}, {'time': 0, 'status': 'passed', 'action': ''}]}]}, {'time': 143, 'status': 'passed', 'action': 'Verify Be In Charge Container', 'steps': [{'time': 67, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 40, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 32, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}]}, {'time': 84, 'status': 'passed', 'action': 'Verify right banner is displayed', 'steps': [{'time': 65, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 16, 'status': 'passed', 'action': 'Page Should Contain Element'}]}, {'time': 55, 'status': 'passed', 'action': 'Verify right banner is displayed', 'steps': [{'time': 37, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 16, 'status': 'passed', 'action': 'Page Should Contain Element'}]}, {'time': 59, 'status': 'passed', 'action': 'Verify right banner is displayed', 'steps': [{'time': 40, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 17, 'status': 'passed', 'action': 'Page Should Contain Element'}]}, {'time': 56, 'status': 'passed', 'action': 'Verify right banner is displayed', 'steps': [{'time': 39, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 15, 'status': 'passed', 'action': 'Page Should Contain Element'}]}, {'time': 2962, 'status': 'passed', 'action': 'Assign Conversation', 'steps': [{'time': 192, 'status': 'passed', 'action': 'Click On Message', 'steps': [{'time': 192, 'status': 'passed', 'action': 
'Common Click Element', 'steps': [{'time': 49, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 59, 'status': 'passed', 
'action': '${scroll}', 'steps': [{'time': 59, 'status': 'passed', 'action': 'Scroll To Element', 'steps': [{'time': 47, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 10, 'status': 'passed', 'action': 'Execute Javascript'}]}]}, {'time': 76, 'status': 'passed', 'action': 'Click Element'}]}]}, {'time': 368, 'status': 'passed', 'action': 'Common Click Element', 'steps': [{'time': 34, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 23, 'status': 'passed', 'action': '${scroll}', 'steps': [{'time': 22, 'status': 'passed', 'action': 'Scroll 
To Element', 'steps': [{'time': 12, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 7, 'status': 'passed', 'action': 'Execute Javascript'}]}]}, {'time': 306, 'status': 'passed', 'action': 'Click Element'}]}, {'time': 434, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 1207, 'status': 'passed', 'action': 'Common Input Text', 'steps': [{'time': 397, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 0, 'status': 'passed', 'action': 'Evaluate'}, {'time': 0, 'status': 'blocked', 'action': '"${system}" == "Darwin"', 'steps': [{'time': 0, 'status': 'blocked', 'action': 'Press Keys'}]}, {'time': 372, 'status': 'passed', 'action': '', 'steps': [{'time': 371, 'status': 'passed', 'action': 'Press Keys'}]}, {'time': 429, 'status': 'passed', 'action': 'Input Text'}]}, {'time': 364, 'status': 'passed', 'action': 'Common Click Element', 'steps': [{'time': 247, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 27, 'status': 'passed', 'action': '${scroll}', 'steps': [{'time': 27, 'status': 'passed', 'action': 'Scroll To Element', 'steps': [{'time': 18, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 7, 'status': 'passed', 'action': 'Execute Javascript'}]}]}, {'time': 82, 'status': 'passed', 'action': 'Click Element'}]}, {'time': 229, 'status': 'passed', 'action': 'Common Click Element', 'steps': [{'time': 35, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 21, 'status': 'passed', 'action': '${scroll}', 'steps': [{'time': 21, 'status': 'passed', 'action': 'Scroll To Element', 'steps': [{'time': 10, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 9, 'status': 'passed', 'action': 'Execute Javascript'}]}]}, {'time': 162, 'status': 'passed', 'action': 'Click Element'}]}, {'time': 159, 'status': 'passed', 'action': 'Common Click Element', 'steps': [{'time': 31, 'status': 'passed', 'action': 'Wait Until Element Is Visible'}, {'time': 23, 'status': 'passed', 'action': '${scroll}', 
'steps': [{'time': 21, 'status': 'passed', 'action': 'Scroll To Element', 'steps': [{'time': 12, 'status': 'passed', 'action': 'Get WebElement'}, {'time': 8, 'status': 'passed', 'action': 'Execute Javascript'}]}]}, {'time': 100, 'status': 'passed', 'action': 'Click Element'}]}]}], 'param': {}, 'defect': False, 'case': {'title': 'End User Send A Message To Start Conversation via LINE', 'description': '', 'preconditions': None, 'postconditions': None, 'suite_title': 'Chat Flow'}}
[Qase][00:31:04][debug] Run completed


[Qase][00:31:04][error] Error at sending results for run 229: 'charmap' codec can't encode characters in position 293-297: character maps to <undefined>
[Qase][00:31:04][info] Overhead for Qase Report: 3160ms


Exception in thread Thread-3 (_send_results_threaded):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\reporters\testops.py", line 76, in _send_results_threaded 
    self.client.send_results(self.project_code, self.run_id, results)
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\client\api_v1_client.py", line 125, in send_results       
    results_to_send = [self._prepare_result(project_code, result) for result in results]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\client\api_v1_client.py", line 125, in <listcomp>
    results_to_send = [self._prepare_result(project_code, result) for result in results]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\client\api_v1_client.py", line 188, in _prepare_result    
    self.logger.log_debug(f"Prepared result: {result_model}")
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\logger.py", line 27, in log_debug
    self.log(message, 'debug')
  File "D:\JungPham\project\tests\e2e-testing\venv\Lib\site-packages\qase\commons\logger.py", line 23, in log
    f.write(log)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 293-297: character maps to <undefined>
```

=> I find the error at some results has `'action': ''`

How can I bypass the error when the value is empty?

**Comment by gibiw** [comment] 2024-08-23 07:20
@JungPham Thank you for your request.
The "action" field cannot be empty. We need to understand why this is happening. 
Can you create a small test project where this problem is reproduced and send it to us?

**Comment by EugeneChangResola** [comment] 2024-08-23 14:02
Hi team, c.c @JungPham 
This one seems can reproduced the same symptom, 
If the keyword or test cases contained "IF ELSE" like below simple test code:

```
*** Test Cases ***
Simple IF ELSE Test
    Open Browser    about:blank    chrome
    IF    '${test_region}' == 'jp'
        Go To   http://www.google.co.jp
    ELSE
        Go To   https://www.google.com
    END
```


and if replace "ELSE" to "ESLE IF" like below sample, 
It won't encountered the error and sent the result into qase test run correctly for your refereneces.
```
*** Test Cases ***
Replace ELSE to ELSE IF 
    Open Browser    about:blank    ${test_browser}
    IF    '${test_region}' == 'jp'
        Go To   http://www.google.co.jp
    ELSE IF   '${test_region}' != 'jp'
        Go To   https://www.google.com
    END
```

**Comment by gibiw** [comment] 2024-08-28 14:55
We have released a beta version of the reporter with a fix for this issue. Try updating to version `qase-robotframework 3.1.1b1`
The constructions `IF`, `ELSE`, etc. will be ignored. Only running steps will be added to the test.

**Comment by gibiw** [comment] 2024-09-02 08:56
@JungPham @EugeneChangResola Hi! Can you provide feedback on this fix?

**Comment by gibiw** [comment] 2024-09-04 11:07
@JungPham try to update the qase-robotframework to 3.1.1b2 version

**Comment by gibiw** [comment] 2024-09-04 14:20
@JungPham what version of `qase-python-commons` package are you using? If it's not the latest, then try updating to the latest and check again.

**Comment by gibiw** [comment] 2024-09-05 07:07
@JungPham We can't reproduce this problem, but we have some ideas on how to fix it. Can you email us at [support@qase.io](mailto:support@qase.io) and we'll send you a temporary package for testing?

**Comment by gibiw** [comment] 2024-09-09 14:22
@JungPham try to update `qase-robotframework` to 3.1.1 version

**Comment by gibiw** [comment] 2024-09-30 14:54
@JungPham Hi! Is the problem resolved?

**Closed** 2024-10-03 08:54 UTC
