### ISSUE TITLE
'NoneType' object is not iterable  when expected file not found

### ISSUE THREAD

**Issue by safiyayunaeva** [qase-tms/qase-python#304] opened 2024-11-21 23:38 UTC
Upload fails if qase-pytest can't find file in a specific directory.

```
/lib/python3.12/site-packages/qase/commons/reporters/testops.py", line 79, in _send_results_threaded
self.client.send_results(self.project_code, self.run_id, results)
File "/lib/python3.12/site-packages/qase/commons/client/api_v2_client.py", line 49, in send_results
results_to_send = [self._prepare_result(project_code, result) for result in results]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lib/python3.12/site-packages/qase/commons/client/api_v2_client.py", line 59, in _prepare_result
attached.extend(self._upload_attachment(project_code, attachment))
TypeError: 'NoneType' object is not iterable
```
I test a quick fix - catch and log exception in `packages/qase/commons/client/api_v2_client.py` :

```
def _prepare_result(self, project_code: str, result: Result) -> ResultCreate:
        attached = []
        if result.attachments:
            for attachment in result.attachments:
                try:
                    attached.extend(self._upload_attachment(project_code, attachment))
                except Exception as e:
                    self.logger.log(f"Error at uploading attachment: {e}", "info")
```
However, there is mirth be a better solution.

**Comment by gibiw** [comment] 2024-11-22 08:14
@safiyayunaeva Hi! Thanks for reporting the issue and preparing a fix. The issue is fixed in version `3.2.2` of the `qase-python-commons` package

**Closed by gibiw** 2024-11-22 08:14 UTC
